#!/usr/bin/python

import sys

try:
  import peach.agent
except ImportError, e:
  import os.path
  sys.path.append(os.path.join(os.path.dirname(sys.argv[0]), '..'))
  import peach.agent

if __name__ == '__main__':
  sys.exit(peach.agent.main(sys.argv[1:]))
